
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,   
    Over18                  BOOLEAN  NOT NULL,
   CurrentlyPregnant       BOOLEAN  NOT NULL,
   DrsCare                 BOOLEAN  NOT NULL,
   InjuryStatus            BOOLEAN  NOT NULL,
   Age = DB.Column(DB.Integer, nullable=False),
   Weight                  INTEGER  NOT NULL,
   Water                   INTEGER  NOT NULL,
   PhoneTime               INTEGER  NOT NULL,
   CompTime                INTEGER  NOT NULL,
   DriveTime               INTEGER  NOT NULL,
   SittingTime             INTEGER  NOT NULL,
   StandingTime            INTEGER  NOT NULL,
   WalkingTime             INTEGER  NOT NULL,
   RunningTime             INTEGER  NOT NULL,
   BikingTime              INTEGER  NOT NULL,
   ExerciseTime            INTEGER  NOT NULL,
   StretchingTime          INTEGER  NOT NULL,
   SleepingTime            INTEGER  NOT NULL,
   WorkingTime             INTEGER  NOT NULL,
   Digestion               BOOLEAN  NOT NULL,
   Stamina                 BOOLEAN  NOT NULL,
   Mood                    BOOLEAN  NOT NULL,
   Headaches               BOOLEAN  NOT NULL,
   Fallen                  BOOLEAN  NOT NULL,
   HeadTrauma              BOOLEAN  NOT NULL,
   PainLevel               INTEGER  NOT NULL,
   SleepPose               INTEGER  NOT NULL,
   DrivePose               INTEGER  NOT NULL,
   WorkPose                INTEGER  NOT NULL



           CREATE TABLE selfcare_table (
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,   
            Over18                  STRING  NOT NULL,
            CurrentlyPregnant       STRING  NOT NULL,
            DrsCare                 STRING  NOT NULL,
            InjuryStatus            STRING  NOT NULL,
            Age                     INTEGER  NOT NULL,
            Weight                  INTEGER  NOT NULL,
            Water                   INTEGER  NOT NULL,
            PhoneTime               INTEGER  NOT NULL,
            CompTime                INTEGER  NOT NULL,
            DriveTime               INTEGER  NOT NULL,
            SittingTime             INTEGER  NOT NULL,
            StandingTime            INTEGER  NOT NULL,
            WalkingTime             INTEGER  NOT NULL,
            RunningTime             INTEGER  NOT NULL,
            BikingTime              INTEGER  NOT NULL,
            ExerciseTime            INTEGER  NOT NULL,
            StretchingTime          INTEGER  NOT NULL,
            SleepingTime            INTEGER  NOT NULL,
            WorkingTime             INTEGER  NOT NULL,
            Digestion               STRING  NOT NULL,
            Stamina                 STRING  NOT NULL,
            Mood                    STRING  NOT NULL,
            Headaches               STRING  NOT NULL,
            Fallen                  STRING  NOT NULL,
            HeadTrauma              STRING  NOT NULL,
            PainLevel               INTEGER  NOT NULL,
            SleepPose               STRING  NOT NULL,
            DrivePose               STRING  NOT NULL,
            WorkPose                STRING  NOT NULL
            )

            '''